SELECT t.id,
       q1 AS resposta,
       textParser,
       textoParserEmoticom AS textoCompleto,
       hashtags,
       emoticonPos,
       emoticonNeg,
       sentiment,
       sentimentH,
       localCount,
       organizationCount,
       moneyCount,
       personCount,
       erroParseado AS numeroErros,
       numeroConjuncoes,
       taxaSubstantivo,
       taxaAdjetivo,
       taxaAdverbio,
       taxaVerbo,
       palavroes,
       hora,
       tl.name AS nomeEstabelecimento,
       tl.category AS categoriaEstabelecimento,
       diaSemana,

  (SELECT GROUP_CONCAT(ty.subject)
   FROM tweets_nlp tn
   JOIN conceito c ON c.palavra = tn.palavra
   JOIN resource_type ty ON ty.resource = c.resource
   WHERE tn.idTweetInterno = t.idInterno
     AND ty.`type` IN ('http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#SocialPerson',
                       'http://schema.org/Organization',
                       'http://dbpedia.org/ontology/Group',
                       'http://schema.org/MusicGroup',
                       'http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#NaturalPerson',
                       'http://schema.org/Product',
                       'http://dbpedia.org/class/yago/Rocket104099429',
                       'http://dbpedia.org/class/yago/Holder110180178',
                       'http://dbpedia.org/ontology/Artist',
                       'http://dbpedia.org/class/yago/Female109619168',
                       'http://dbpedia.org/class/yago/Child109918248',
                       'http://dbpedia.org/class/yago/Male109624168',
                       'http://dbpedia.org/class/yago/Document103217458',
                       'http://dbpedia.org/class/yago/AthleticFacility102752311',
                       'http://dbpedia.org/class/yago/Pool103982060',
                       'http://dbpedia.org/class/yago/PlasticArt103958097',
                       'http://dbpedia.org/class/yago/SolidFigure113863473',
                       'http://dbpedia.org/class/yago/Attacker109821253',
                       'http://dbpedia.org/class/yago/AcousticDevice102676261',
                       'http://dbpedia.org/class/yago/SignalingDevice104217718',
                       'http://dbpedia.org/class/yago/Anomaly114505821',
                       'http://dbpedia.org/class/yago/Defect114464005',
                       'http://dbpedia.org/class/yago/Climber113102409',
                       'http://dbpedia.org/class/yago/ComputerUser109951274',
                       'http://dbpedia.org/class/yago/Engineer109615807',
                       'http://dbpedia.org/class/yago/RootVegetable107710283',
                       'http://dbpedia.org/class/yago/SolanaceousVegetable107710007',
                       'http://dbpedia.org/class/yago/Stimulant104320126',
                       'http://dbpedia.org/class/yago/Ceramic102997391',
                       'http://dbpedia.org/class/yago/Biome107941945')
   GROUP BY t.id) AS entidades,

  (SELECT GROUP_CONCAT(ty.type)
   FROM tweets_gram tn
   JOIN conceito c ON c.palavra = tn.palavra
   JOIN resource_type ty ON ty.resource = c.resource
   WHERE tn.idTweetInterno = t.idInterno
     AND ty.`type` IN ('http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#SocialPerson',
                       'http://schema.org/Organization',
                       'http://dbpedia.org/ontology/Group',
                       'http://schema.org/MusicGroup',
                       'http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#NaturalPerson',
                       'http://schema.org/Product',
                       'http://dbpedia.org/class/yago/Rocket104099429',
                       'http://dbpedia.org/class/yago/Holder110180178',
                       'http://dbpedia.org/ontology/Artist',
                       'http://dbpedia.org/class/yago/Female109619168',
                       'http://dbpedia.org/class/yago/Child109918248',
                       'http://dbpedia.org/class/yago/Male109624168',
                       'http://dbpedia.org/class/yago/Document103217458',
                       'http://dbpedia.org/class/yago/AthleticFacility102752311',
                       'http://dbpedia.org/class/yago/Pool103982060',
                       'http://dbpedia.org/class/yago/PlasticArt103958097',
                       'http://dbpedia.org/class/yago/SolidFigure113863473',
                       'http://dbpedia.org/class/yago/Attacker109821253',
                       'http://dbpedia.org/class/yago/AcousticDevice102676261',
                       'http://dbpedia.org/class/yago/SignalingDevice104217718',
                       'http://dbpedia.org/class/yago/Anomaly114505821',
                       'http://dbpedia.org/class/yago/Defect114464005',
                       'http://dbpedia.org/class/yago/Climber113102409',
                       'http://dbpedia.org/class/yago/ComputerUser109951274',
                       'http://dbpedia.org/class/yago/Engineer109615807',
                       'http://dbpedia.org/class/yago/RootVegetable107710283',
                       'http://dbpedia.org/class/yago/SolanaceousVegetable107710007',
                       'http://dbpedia.org/class/yago/Stimulant104320126',
                       'http://dbpedia.org/class/yago/Ceramic102997391',
                       'http://dbpedia.org/class/yago/Biome107941945')
   GROUP BY t.id) AS grams
FROM tweets t
LEFT JOIN tweet_localizacao tl ON tl.idTweetInterno = t.idInterno
AND distance = 100